name: 'Environment Variables from AWS Parameter Store'
description: 'Set workflow environment variables from values in AWS Parameter Store.'
author: 'Sean Fern'
inputs:
  params:
    required: true
    description: 'Whitespace-separated parameters of the form ENV_VAR=/aws/parameter/name'
runs:
  using: 'node16'
  main: 'dist/index.js'
