name: 'AWS Parameter Store Environment Variables'
description: 'Set workflow environment variables from values in AWS Parameter Store. Parameters of type SecureString are automatically masked.'
author: 'Sean Fern'
inputs:
  params:
    required: true
    description: 'Whitespace-separated parameters of the form ENV_VAR=/aws/parameter/name'
runs:
  using: 'node16'
  main: 'dist/index.js'
